# Generated by Django 3.2.3 on 2021-06-06 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logwaste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewaste',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
