# Generated by Django 3.2.3 on 2021-06-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logwaste', '0002_ewaste_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.IntegerField()),
                ('bill_amount', models.IntegerField()),
                ('bill_month', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
