# Generated by Django 3.2.3 on 2021-06-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logwaste', '0003_bills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='date',
        ),
    ]
