# Generated by Django 3.2.3 on 2021-06-08 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logwaste', '0004_remove_bills_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='bill_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
