# Generated by Django 3.2.3 on 2021-06-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logwaste', '0005_bills_bill_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
