# Generated by Django 3.2.3 on 2021-06-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logwaste', '0006_delete_bills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.IntegerField()),
                ('bill_amount', models.IntegerField()),
                ('bill_month', models.CharField(max_length=10)),
                ('bill_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='ewaste',
            name='date',
            field=models.DateField(),
        ),
    ]
