# Generated by Django 3.2.3 on 2021-06-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logwaste', '0007_auto_20210608_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ewaste',
        ),
    ]
