# Generated by Django 3.2.3 on 2021-06-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logwaste', '0009_ewaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickedEwaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=30)),
                ('item_description', models.CharField(max_length=100)),
                ('item_image', models.ImageField(upload_to='media')),
                ('date', models.DateField()),
                ('picked_date', models.DateField()),
            ],
        ),
    ]
