# Generated by Django 3.2.3 on 2021-06-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logwaste', '0010_pickedewaste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickedEwaste',
        ),
    ]
